name: Test with Python 2.x

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 2
    - name: start server
      run: python app.py & sleep 10 && curl -X POST http://localhost:1024
