name: Test on Python 2.x and 3.x

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_ver: [2, 3]
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_ver }}
    - name: start server
      run: python app.py
